spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}-group
      #group-id: user-service-group
#      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

      properties:
        "[spring.json.value.default.type]": com.ashimCS.learnKafka.notification_service.event.UserCreatedEvent   #What Java class should I create?
        "[spring.json.trusted.packages]": com.ashimCS.learnKafka.notification_service.event    #Am I allowed to create classes from this package?

logging:
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"